name: Build and Push Docker Image to Alibaba Cloud ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 显式配置 Docker DNS
      - name: Set up Docker Buildx with DNS
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."crpi-j82a4dxirz282twg.cn-guangzhou.personal.cr.aliyuncs.com/jianluo_docker/sais_medicine_rna"]
              mirrors = ["crpi-j82a4dxirz282twg.cn-guangzhou.personal.cr.aliyuncs.com/jianluo_docker/sais_medicine_rna"]
            [dns]
              nameservers = ["8.8.8.8", "1.1.1.1"]

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_REGISTRY }}/jianluo_docker/sais_medicine_rna:latest .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/jianluo_docker/sais_medicine_rna:latest
